name: stlBuilder
on: push
jobs:
  cableHolder:
    runs-on: ubuntu-latest
    steps:
    -   name: Setup
        uses: actions/checkout@v2
    - name: Build stl file
      uses: flat35hd99/openscad-actions@v1.4
      with:
        scad_file: ./cableHolder.scad
        output_file: ./stls/cableHolder.stl
