name: stlBuilder
on: push
jobs:
  cableHolder:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: actions/checkout@v3
    - name: Build stl files
      uses: eXpire163/openscad-actions@main
      with:
        scad_file: ./
        output_file: ./stls/
        target_format_for_bulk: stl
    - name: Build png files
      uses: eXpire163/openscad-actions@main
      with:
        scad_file: ./
        output_file: ./pngs/
        target_format_for_bulk: png
        options: "--render --colorscheme DeepOcean"
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: "['./stls/*.stl', './pngs/*.png']"
