name: stlBuilder
on: push
jobs:
  cableHolder:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: actions/checkout@v4
    - name: Build stl file
      uses: eXpire163/openscad-actions@main
      with:
        scad_file: ./
        output_file: ./stls/
    - name: artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./stls/
    - name: Upload stl file
      uses: EndBug/add-and-commit@v9
      with:
        message: test
        add: './stls'
    
