name: stlBuilder
on: push
jobs:
  cableHolder:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: actions/checkout@v4
    - name: Build stl file
      uses: flat35hd99/openscad-actions@v1.4
      with:
        scad_file: cableHolder.scad
        output_file: stls/cableHolder.stl
    - name: Upload stl file as artifact
      uses: EndBug/add-and-commit@v9
      with:
        message :test
    
