name: socketHolderBuilder
on: workflow_dispatch
jobs:
  cableHolder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        selectParm: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    steps:
    - name: Setup
      uses: actions/checkout@v3
    - name: Build stl files
      uses: eXpire163/openscad-actions@main
      with:
        scad_file: ./SocketHolder.scad
        output_file: join([ './stls/SocketHolder',${{matrix.selectParm}},'.stl'],"")
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: "['./stls/*.stl']"
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./stls
